title: Commonwealth Cushaw
description: An open repostory of information about cushaw squash from seed to plate
theme: just-the-docs

url: https://markwkidd.github.io
#baseurl: cushaw-handbook # needed when the pages are served from a subfolder, like on github.io
repository: markwkidd/crop-guides # for github-metadata

permalink: pretty

aux_links:
  Commonwealth Cushaw Facebook Group: https://www.facebook.com/groups/commonwealthcushaw
  Going to Seed Courses and Community: https://goingtoseed.org/

search_enabled: false

# Set a path/url to a logo that will be displayed instead of the title
logo: "assets/images/commonwealth-cushaw-logo-white-500x180.png"

footer_content: "Copyright &copy; Going to Seed and Handbarrow. Published with a <a href=\"https://creativecommons.org/licenses/by/4.0/\">CC BY 4.0 License.</a>"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/markwkidd/cushaw-handbook" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: light

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  idea:
    title: Idea
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
